config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_editorconfig:
    src: editorconfig
    dst: ~/.editorconfig
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitmux.conf:
    src: gitmux.conf
    dst: ~/.gitmux.conf
profiles:
  s1:
    dotfiles:
    - f_editorconfig
    - f_init.vim
    - f_alacritty.yml
    - f_tmux.conf
    - f_bashrc
    - f_gitmux.conf
