#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
colorscheme = "gruvbox"
colorscheme_bg = "dark"
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
filetree_direction = "left"
enable_statusline_mode = false
relativenumber = false

# left sections of statusline
statusline_left_sections = [
  'winnr',
  'filename',
]
# right sections of statusline
statusline_right_sections = [
  'cursorpos',
  'fileformat',
]

bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"
enable = true

[[layers]]
name = "core#statusline"

[[layers]]
name = "lsp"
filetypes = [
  "rust"
]

[[layers]]
name = "ctrlp"

# language support
[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#sh"

[[layers]]
name = "format"

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = 'tmux'
